# Generated by Django 3.2 on 2023-09-30 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_alter_personfilmwork_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filmwork',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='filmwork',
            old_name='updated_at',
            new_name='modified',
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='updated_at',
            new_name='modified',
        ),
        migrations.RenameField(
            model_name='genrefilmwork',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='updated_at',
            new_name='modified',
        ),
        migrations.RenameField(
            model_name='personfilmwork',
            old_name='created_at',
            new_name='created',
        ),
    ]
